/**
 * Database types for Supabase
 * Clean schema - matches 001_clean_schema.sql
 */

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          role: 'client' | 'therapist' | 'admin';
          full_name: string | null;
          phone: string | null;
          country: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          role?: 'client' | 'therapist' | 'admin';
          full_name?: string | null;
          phone?: string | null;
          country?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          role?: 'client' | 'therapist' | 'admin';
          full_name?: string | null;
          phone?: string | null;
          country?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      bookings: {
        Row: {
          id: string;
          user_id: string | null;
          name: string;
          email: string;
          phone: string;
          country: string;
          therapist_id: string;
          therapist_name: string;
          therapist_user_id: string | null;
          date: string;
          time: string;
          type: 'free_consultation' | 'program';
          program_id: string | null;
          meeting_link: string | null;
          status: 'confirmed' | 'cancelled' | 'completed' | 'scheduled' | 'no_show' | 'pending';
          session_number: number | null;
          reschedule_count: number;
          cancelled_at: string | null;
          created_at: string;
          updated_at: string | null;
          rescheduled_from_date: string | null;
          rescheduled_from_time: string | null;
          google_calendar_event_id: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          name: string;
          email: string;
          phone?: string;
          country?: string;
          therapist_id: string;
          therapist_name: string;
          therapist_user_id?: string | null;
          date: string;
          time: string;
          type?: 'free_consultation' | 'program';
          program_id?: string | null;
          meeting_link?: string | null;
          status?: 'confirmed' | 'cancelled' | 'completed' | 'scheduled' | 'no_show' | 'pending';
          session_number?: number | null;
          reschedule_count?: number;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string | null;
          rescheduled_from_date?: string | null;
          rescheduled_from_time?: string | null;
          google_calendar_event_id?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          name?: string;
          email?: string;
          phone?: string;
          country?: string;
          therapist_id?: string;
          therapist_name?: string;
          therapist_user_id?: string | null;
          date?: string;
          time?: string;
          type?: 'free_consultation' | 'program';
          program_id?: string | null;
          meeting_link?: string | null;
          status?: 'confirmed' | 'cancelled' | 'completed' | 'scheduled' | 'no_show' | 'pending';
          session_number?: number | null;
          reschedule_count?: number;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string | null;
          rescheduled_from_date?: string | null;
          rescheduled_from_time?: string | null;
          google_calendar_event_id?: string | null;
        };
        Relationships: [];
      };
      programs: {
        Row: {
          id: string;
          user_id: string | null;
          total_sessions: number;
          used_sessions: number;
          sessions_completed: number;
          status: 'active' | 'completed' | 'cancelled';
          payment_id: string;
          therapist_user_id: string | null;
          therapist_name: string | null;
          program_type: 'private' | 'group' | null;
          price_paid: number | null;
          client_name: string | null;
          client_email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          total_sessions: number;
          used_sessions?: number;
          sessions_completed?: number;
          status?: 'active' | 'completed' | 'cancelled';
          payment_id: string;
          therapist_user_id?: string | null;
          therapist_name?: string | null;
          program_type?: 'private' | 'group' | null;
          price_paid?: number | null;
          client_name?: string | null;
          client_email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          total_sessions?: number;
          used_sessions?: number;
          sessions_completed?: number;
          status?: 'active' | 'completed' | 'cancelled';
          payment_id?: string;
          therapist_user_id?: string | null;
          therapist_name?: string | null;
          program_type?: 'private' | 'group' | null;
          price_paid?: number | null;
          client_name?: string | null;
          client_email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      sessions: {
        Row: {
          id: string;
          program_id: string;
          booking_id: string | null;
          client_id: string | null;
          therapist_id: string | null;
          date_time: string | null;
          meet_link: string | null;
          session_number: number;
          date: string | null;
          time: string | null;
          status: 'scheduled' | 'completed' | 'cancelled' | 'pending';
          notes: string | null;
          is_complete: boolean;
          development_form_submitted: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          program_id: string;
          booking_id?: string | null;
          client_id?: string | null;
          therapist_id?: string | null;
          date_time?: string | null;
          meet_link?: string | null;
          session_number: number;
          date?: string | null;
          time?: string | null;
          status?: 'scheduled' | 'completed' | 'cancelled' | 'pending';
          notes?: string | null;
          is_complete?: boolean;
          development_form_submitted?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          program_id?: string;
          booking_id?: string | null;
          client_id?: string | null;
          therapist_id?: string | null;
          date_time?: string | null;
          meet_link?: string | null;
          session_number?: number;
          date?: string | null;
          time?: string | null;
          status?: 'scheduled' | 'completed' | 'cancelled' | 'pending';
          notes?: string | null;
          is_complete?: boolean;
          development_form_submitted?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'sessions_program_id_fkey';
            columns: ['program_id'];
            referencedRelation: 'programs';
            referencedColumns: ['id'];
          }
        ];
      };
      diagnostic_assessments: {
        Row: {
          id: string;
          client_id: string;
          therapist_id: string;
          session_id: string | null;
          is_baseline: boolean;
          client_name: string | null;
          date_of_birth: string | null;
          client_email: string | null;
          client_phone: string | null;
          client_country: string | null;
          client_occupation: string | null;
          relationship_status: string | null;
          main_complaint: string;
          current_symptoms: string[];
          previous_therapy: boolean;
          previous_therapy_details: string | null;
          nervous_system_pattern: 'regulated' | 'hyper' | 'hypo' | 'mixed' | null;
          emotional_patterns: Record<string, unknown>[];
          cognitive_patterns: Record<string, unknown>[];
          body_symptoms: Record<string, unknown>[];
          behavioral_patterns: Record<string, unknown>[];
          life_functioning_patterns: Record<string, unknown>[];
          nervous_system_score: number;
          emotional_state_score: number;
          cognitive_patterns_score: number;
          body_symptoms_score: number;
          behavioral_patterns_score: number;
          life_functioning_score: number;
          goal_readiness_score: number;
          root_cause_pattern_timeline: string | null;
          root_cause_parental_influence: string | null;
          root_cause_core_patterns: string | null;
          root_cause_contributing_factors: string | null;
          clinical_condition_brief: string | null;
          therapist_focus: string | null;
          therapy_goal: string | null;
          assessed_at: string;
          status: 'draft' | 'submitted';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          therapist_id: string;
          session_id?: string | null;
          is_baseline?: boolean;
          client_name?: string | null;
          date_of_birth?: string | null;
          client_email?: string | null;
          client_phone?: string | null;
          client_country?: string | null;
          client_occupation?: string | null;
          relationship_status?: string | null;
          main_complaint: string;
          current_symptoms?: string[];
          previous_therapy?: boolean;
          previous_therapy_details?: string | null;
          nervous_system_pattern?: 'regulated' | 'hyper' | 'hypo' | 'mixed' | null;
          emotional_patterns?: Record<string, unknown>[];
          cognitive_patterns?: Record<string, unknown>[];
          body_symptoms?: Record<string, unknown>[];
          behavioral_patterns?: Record<string, unknown>[];
          life_functioning_patterns?: Record<string, unknown>[];
          nervous_system_score?: number;
          emotional_state_score?: number;
          cognitive_patterns_score?: number;
          body_symptoms_score?: number;
          behavioral_patterns_score?: number;
          life_functioning_score?: number;
          root_cause_pattern_timeline?: string | null;
          root_cause_parental_influence?: string | null;
          root_cause_core_patterns?: string | null;
          root_cause_contributing_factors?: string | null;
          clinical_condition_brief?: string | null;
          therapist_focus?: string | null;
          therapy_goal?: string | null;
          assessed_at?: string;
          status?: 'draft' | 'submitted';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          therapist_id?: string;
          session_id?: string | null;
          is_baseline?: boolean;
          client_name?: string | null;
          date_of_birth?: string | null;
          client_email?: string | null;
          client_phone?: string | null;
          client_country?: string | null;
          client_occupation?: string | null;
          relationship_status?: string | null;
          main_complaint?: string;
          current_symptoms?: string[];
          previous_therapy?: boolean;
          previous_therapy_details?: string | null;
          nervous_system_pattern?: 'regulated' | 'hyper' | 'hypo' | 'mixed' | null;
          emotional_patterns?: Record<string, unknown>[];
          cognitive_patterns?: Record<string, unknown>[];
          body_symptoms?: Record<string, unknown>[];
          behavioral_patterns?: Record<string, unknown>[];
          life_functioning_patterns?: Record<string, unknown>[];
          nervous_system_score?: number;
          emotional_state_score?: number;
          cognitive_patterns_score?: number;
          body_symptoms_score?: number;
          behavioral_patterns_score?: number;
          life_functioning_score?: number;
          root_cause_pattern_timeline?: string | null;
          root_cause_parental_influence?: string | null;
          root_cause_core_patterns?: string | null;
          root_cause_contributing_factors?: string | null;
          clinical_condition_brief?: string | null;
          therapist_focus?: string | null;
          therapy_goal?: string | null;
          assessed_at?: string;
          status?: 'draft' | 'submitted';
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      session_development_forms: {
        Row: {
          id: string;
          session_id: string;
          client_id: string;
          therapist_id: string;
          session_number: number;
          session_date: string;
          previous_session_improvements: string | null;
          previous_session_challenges: string | null;
          pre_session_symptoms: Record<string, unknown>[];
          pre_session_intensity: number;
          techniques_used: Record<string, unknown>[];
          key_interventions: string | null;
          breakthroughs_resistance: string | null;
          post_session_symptoms: Record<string, unknown>[];
          post_session_intensity: number;
          shift_observed: string | null;
          client_feedback: string | null;
          integration_notes: string | null;
          therapist_internal_notes: string | null;
          nervous_system_score: number;
          emotional_state_score: number;
          cognitive_patterns_score: number;
          body_symptoms_score: number;
          behavioral_patterns_score: number;
          life_functioning_score: number;
          goal_readiness_score: number;
          submitted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          client_id: string;
          therapist_id: string;
          session_number: number;
          session_date: string;
          previous_session_improvements?: string | null;
          previous_session_challenges?: string | null;
          pre_session_symptoms?: Record<string, unknown>[];
          pre_session_intensity?: number;
          techniques_used?: Record<string, unknown>[];
          key_interventions?: string | null;
          breakthroughs_resistance?: string | null;
          post_session_symptoms?: Record<string, unknown>[];
          post_session_intensity?: number;
          shift_observed?: string | null;
          client_feedback?: string | null;
          integration_notes?: string | null;
          therapist_internal_notes?: string | null;
          nervous_system_score?: number;
          emotional_state_score?: number;
          cognitive_patterns_score?: number;
          body_symptoms_score?: number;
          behavioral_patterns_score?: number;
          life_functioning_score?: number;
          submitted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          client_id?: string;
          therapist_id?: string;
          session_number?: number;
          session_date?: string;
          previous_session_improvements?: string | null;
          previous_session_challenges?: string | null;
          pre_session_symptoms?: Record<string, unknown>[];
          pre_session_intensity?: number;
          techniques_used?: Record<string, unknown>[];
          key_interventions?: string | null;
          breakthroughs_resistance?: string | null;
          post_session_symptoms?: Record<string, unknown>[];
          post_session_intensity?: number;
          shift_observed?: string | null;
          client_feedback?: string | null;
          integration_notes?: string | null;
          therapist_internal_notes?: string | null;
          nervous_system_score?: number;
          emotional_state_score?: number;
          cognitive_patterns_score?: number;
          body_symptoms_score?: number;
          behavioral_patterns_score?: number;
          life_functioning_score?: number;
          submitted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      session_materials: {
        Row: {
          id: string;
          session_id: string;
          type: 'pdf' | 'video';
          url: string;
          filename: string;
          uploaded_by: string;
          uploaded_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          type: 'pdf' | 'video';
          url: string;
          filename: string;
          uploaded_by: string;
          uploaded_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          type?: 'pdf' | 'video';
          url?: string;
          filename?: string;
          uploaded_by?: string;
          uploaded_at?: string;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          name: string;
          mobile: string;
          email: string;
          country: string;
          source: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          mobile: string;
          email: string;
          country: string;
          source?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          mobile?: string;
          email?: string;
          country?: string;
          source?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          user_id: string | null;
          amount: number;
          currency: string;
          type: 'full_program' | 'single_session';
          status: 'pending' | 'paid' | 'failed' | 'refunded';
          payment_reference: string | null;
          program_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          amount: number;
          currency?: string;
          type: 'full_program' | 'single_session';
          status?: 'pending' | 'paid' | 'failed' | 'refunded';
          payment_reference?: string | null;
          program_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          amount?: number;
          currency?: string;
          type?: 'full_program' | 'single_session';
          status?: 'pending' | 'paid' | 'failed' | 'refunded';
          payment_reference?: string | null;
          program_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      therapist_clients: {
        Row: {
          id: string;
          therapist_id: string;
          client_id: string;
          assigned_at: string;
          notes: string | null;
        };
        Insert: {
          id?: string;
          therapist_id: string;
          client_id: string;
          assigned_at?: string;
          notes?: string | null;
        };
        Update: {
          id?: string;
          therapist_id?: string;
          client_id?: string;
          assigned_at?: string;
          notes?: string | null;
        };
        Relationships: [];
      };
      therapist_availability: {
        Row: {
          id: string;
          therapist_id: string;
          day_of_week: number | null;
          start_time: string;
          end_time: string;
          exception_date: string | null;
          is_blocked: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          therapist_id: string;
          day_of_week?: number | null;
          start_time: string;
          end_time: string;
          exception_date?: string | null;
          is_blocked?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          therapist_id?: string;
          day_of_week?: number | null;
          start_time?: string;
          end_time?: string;
          exception_date?: string | null;
          is_blocked?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notifications_log: {
        Row: {
          id: string;
          booking_id: string | null;
          user_id: string | null;
          channel: 'email' | 'whatsapp' | 'sms';
          trigger_type: string;
          recipient_email: string | null;
          recipient_phone: string | null;
          status: 'pending' | 'sent' | 'failed';
          error_message: string | null;
          sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          booking_id?: string | null;
          user_id?: string | null;
          channel: 'email' | 'whatsapp' | 'sms';
          trigger_type: string;
          recipient_email?: string | null;
          recipient_phone?: string | null;
          status?: 'pending' | 'sent' | 'failed';
          error_message?: string | null;
          sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string | null;
          user_id?: string | null;
          channel?: 'email' | 'whatsapp' | 'sms';
          trigger_type?: string;
          recipient_email?: string | null;
          recipient_phone?: string | null;
          status?: 'pending' | 'sent' | 'failed';
          error_message?: string | null;
          sent_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};
